`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 26 2021 12:38:20 CST (Apr 26 2021 04:38:20 UTC)

module SobelFilter_Mul_12Sx8U_12S_4(in2, in1, out1);
  input [11:0] in2;
  input [7:0] in1;
  output [11:0] out1;
  wire [11:0] in2;
  wire [7:0] in1;
  wire [11:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_3,
       mul_22_8_n_4, mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_7;
  wire mul_22_8_n_8, mul_22_8_n_9, mul_22_8_n_10, mul_22_8_n_11,
       mul_22_8_n_12, mul_22_8_n_13, mul_22_8_n_14, mul_22_8_n_16;
  wire mul_22_8_n_17, mul_22_8_n_18, mul_22_8_n_19, mul_22_8_n_20,
       mul_22_8_n_21, mul_22_8_n_22, mul_22_8_n_23, mul_22_8_n_24;
  wire mul_22_8_n_25, mul_22_8_n_26, mul_22_8_n_27, mul_22_8_n_28,
       mul_22_8_n_29, mul_22_8_n_30, mul_22_8_n_31, mul_22_8_n_32;
  wire mul_22_8_n_33, mul_22_8_n_34, mul_22_8_n_35, mul_22_8_n_36,
       mul_22_8_n_37, mul_22_8_n_38, mul_22_8_n_39, mul_22_8_n_40;
  wire mul_22_8_n_41, mul_22_8_n_42, mul_22_8_n_43, mul_22_8_n_44,
       mul_22_8_n_45, mul_22_8_n_46, mul_22_8_n_47, mul_22_8_n_48;
  wire mul_22_8_n_49, mul_22_8_n_50, mul_22_8_n_51, mul_22_8_n_52,
       mul_22_8_n_53, mul_22_8_n_54, mul_22_8_n_55, mul_22_8_n_56;
  wire mul_22_8_n_57, mul_22_8_n_58, mul_22_8_n_59, mul_22_8_n_60,
       mul_22_8_n_61, mul_22_8_n_62, mul_22_8_n_63, mul_22_8_n_64;
  wire mul_22_8_n_65, mul_22_8_n_66, mul_22_8_n_67, mul_22_8_n_68,
       mul_22_8_n_69, mul_22_8_n_70, mul_22_8_n_71, mul_22_8_n_72;
  wire mul_22_8_n_73, mul_22_8_n_74, mul_22_8_n_75, mul_22_8_n_76,
       mul_22_8_n_77, mul_22_8_n_78, mul_22_8_n_79, mul_22_8_n_80;
  wire mul_22_8_n_81, mul_22_8_n_82, mul_22_8_n_83, mul_22_8_n_84,
       mul_22_8_n_85, mul_22_8_n_86, mul_22_8_n_87, mul_22_8_n_88;
  wire mul_22_8_n_89, mul_22_8_n_90, mul_22_8_n_91, mul_22_8_n_92,
       mul_22_8_n_93, mul_22_8_n_94, mul_22_8_n_95, mul_22_8_n_96;
  wire mul_22_8_n_97, mul_22_8_n_98, mul_22_8_n_99, mul_22_8_n_100,
       mul_22_8_n_101, mul_22_8_n_102, mul_22_8_n_103, mul_22_8_n_104;
  wire mul_22_8_n_105, mul_22_8_n_106, mul_22_8_n_107, mul_22_8_n_108,
       mul_22_8_n_109, mul_22_8_n_111, mul_22_8_n_112, mul_22_8_n_113;
  wire mul_22_8_n_114, mul_22_8_n_115, mul_22_8_n_116, mul_22_8_n_117,
       mul_22_8_n_118, mul_22_8_n_119, mul_22_8_n_120, mul_22_8_n_121;
  wire mul_22_8_n_122, mul_22_8_n_123, mul_22_8_n_124, mul_22_8_n_125,
       mul_22_8_n_126, mul_22_8_n_127, mul_22_8_n_128, mul_22_8_n_129;
  wire mul_22_8_n_130, mul_22_8_n_131, mul_22_8_n_132, mul_22_8_n_133,
       mul_22_8_n_135, mul_22_8_n_136, mul_22_8_n_137, mul_22_8_n_138;
  wire mul_22_8_n_139, mul_22_8_n_140, mul_22_8_n_141, mul_22_8_n_142,
       mul_22_8_n_143, mul_22_8_n_144, mul_22_8_n_145, mul_22_8_n_146;
  wire mul_22_8_n_147, mul_22_8_n_148, mul_22_8_n_150, mul_22_8_n_151,
       mul_22_8_n_152, mul_22_8_n_153, mul_22_8_n_154, mul_22_8_n_155;
  wire mul_22_8_n_156, mul_22_8_n_158, mul_22_8_n_159, mul_22_8_n_160,
       mul_22_8_n_161, mul_22_8_n_162, mul_22_8_n_163, mul_22_8_n_164;
  wire mul_22_8_n_165, mul_22_8_n_166, mul_22_8_n_167, mul_22_8_n_168,
       mul_22_8_n_169, mul_22_8_n_170, mul_22_8_n_172, mul_22_8_n_173;
  wire mul_22_8_n_174, mul_22_8_n_176, mul_22_8_n_177, mul_22_8_n_178,
       mul_22_8_n_179, mul_22_8_n_180, mul_22_8_n_182, mul_22_8_n_183;
  wire mul_22_8_n_185, mul_22_8_n_187;
  XNOR2X1 mul_22_8_g2222(.A (mul_22_8_n_182), .B (mul_22_8_n_187), .Y
       (out1[11]));
  ADDFX1 mul_22_8_g2223(.A (mul_22_8_n_185), .B (mul_22_8_n_180), .CI
       (mul_22_8_n_173), .CO (mul_22_8_n_187), .S (out1[10]));
  ADDFX1 mul_22_8_g2224(.A (mul_22_8_n_183), .B (mul_22_8_n_174), .CI
       (mul_22_8_n_165), .CO (mul_22_8_n_185), .S (out1[9]));
  ADDFX1 mul_22_8_g2225(.A (mul_22_8_n_178), .B (mul_22_8_n_166), .CI
       (mul_22_8_n_155), .CO (mul_22_8_n_183), .S (out1[8]));
  XNOR2X1 mul_22_8_g2226(.A (mul_22_8_n_179), .B (mul_22_8_n_158), .Y
       (mul_22_8_n_182));
  XNOR2X1 mul_22_8_g2227(.A (mul_22_8_n_170), .B (mul_22_8_n_177), .Y
       (out1[7]));
  ADDFX1 mul_22_8_g2228(.A (mul_22_8_n_147), .B (mul_22_8_n_146), .CI
       (mul_22_8_n_122), .CO (mul_22_8_n_179), .S (mul_22_8_n_180));
  OAI211X1 mul_22_8_g2229(.A0 (mul_22_8_n_160), .A1 (mul_22_8_n_161),
       .B0 (mul_22_8_n_176), .C0 (mul_22_8_n_172), .Y (mul_22_8_n_178));
  OAI21X1 mul_22_8_g2230(.A0 (mul_22_8_n_162), .A1 (mul_22_8_n_169),
       .B0 (mul_22_8_n_160), .Y (mul_22_8_n_177));
  AOI21X1 mul_22_8_g2231(.A0 (mul_22_8_n_151), .A1 (mul_22_8_n_167),
       .B0 (mul_22_8_n_163), .Y (mul_22_8_n_176));
  XNOR2X1 mul_22_8_g2232(.A (mul_22_8_n_168), .B (mul_22_8_n_169), .Y
       (out1[6]));
  ADDFX1 mul_22_8_g2233(.A (mul_22_8_n_139), .B (mul_22_8_n_128), .CI
       (mul_22_8_n_148), .CO (mul_22_8_n_173), .S (mul_22_8_n_174));
  NAND2XL mul_22_8_g2234(.A (mul_22_8_n_159), .B (mul_22_8_n_167), .Y
       (mul_22_8_n_172));
  XNOR2X1 mul_22_8_g2235(.A (mul_22_8_n_144), .B (mul_22_8_n_164), .Y
       (out1[5]));
  OR2XL mul_22_8_g2236(.A (mul_22_8_n_163), .B (mul_22_8_n_161), .Y
       (mul_22_8_n_170));
  NOR2X1 mul_22_8_g2237(.A (mul_22_8_n_159), .B (mul_22_8_n_151), .Y
       (mul_22_8_n_169));
  NOR2BX1 mul_22_8_g2238(.AN (mul_22_8_n_160), .B (mul_22_8_n_162), .Y
       (mul_22_8_n_168));
  NOR2X1 mul_22_8_g2239(.A (mul_22_8_n_162), .B (mul_22_8_n_161), .Y
       (mul_22_8_n_167));
  ADDFX1 mul_22_8_g2240(.A (mul_22_8_n_132), .B (mul_22_8_n_129), .CI
       (mul_22_8_n_140), .CO (mul_22_8_n_165), .S (mul_22_8_n_166));
  NAND2X1 mul_22_8_g2241(.A (mul_22_8_n_126), .B (mul_22_8_n_152), .Y
       (mul_22_8_n_164));
  AND2XL mul_22_8_g2242(.A (mul_22_8_n_153), .B (mul_22_8_n_156), .Y
       (mul_22_8_n_163));
  NOR2X1 mul_22_8_g2243(.A (mul_22_8_n_137), .B (mul_22_8_n_154), .Y
       (mul_22_8_n_162));
  NOR2X1 mul_22_8_g2244(.A (mul_22_8_n_153), .B (mul_22_8_n_156), .Y
       (mul_22_8_n_161));
  NAND2X1 mul_22_8_g2245(.A (mul_22_8_n_137), .B (mul_22_8_n_154), .Y
       (mul_22_8_n_160));
  NOR2X1 mul_22_8_g2246(.A (mul_22_8_n_141), .B (mul_22_8_n_152), .Y
       (mul_22_8_n_159));
  XNOR2X1 mul_22_8_g2247(.A (mul_22_8_n_145), .B (mul_22_8_n_143), .Y
       (mul_22_8_n_158));
  XNOR2X1 mul_22_8_g2248(.A (mul_22_8_n_150), .B (mul_22_8_n_136), .Y
       (out1[4]));
  ADDFX1 mul_22_8_g2249(.A (mul_22_8_n_123), .B (mul_22_8_n_114), .CI
       (mul_22_8_n_130), .CO (mul_22_8_n_155), .S (mul_22_8_n_156));
  ADDFX1 mul_22_8_g2250(.A (mul_22_8_n_124), .B (mul_22_8_n_76), .CI
       (mul_22_8_n_117), .CO (mul_22_8_n_153), .S (mul_22_8_n_154));
  NAND2BX1 mul_22_8_g2251(.AN (mul_22_8_n_125), .B (mul_22_8_n_150), .Y
       (mul_22_8_n_152));
  OAI21X1 mul_22_8_g2252(.A0 (mul_22_8_n_126), .A1 (mul_22_8_n_141),
       .B0 (mul_22_8_n_142), .Y (mul_22_8_n_151));
  ADDFX1 mul_22_8_g2253(.A (mul_22_8_n_133), .B (mul_22_8_n_91), .CI
       (mul_22_8_n_115), .CO (mul_22_8_n_150), .S (out1[3]));
  ADDFX1 mul_22_8_g2254(.A (mul_22_8_n_131), .B (mul_22_8_n_104), .CI
       (mul_22_8_n_74), .CO (mul_22_8_n_147), .S (mul_22_8_n_148));
  ADDFX1 mul_22_8_g2255(.A (mul_22_8_n_127), .B (mul_22_8_n_101), .CI
       (mul_22_8_n_102), .CO (mul_22_8_n_145), .S (mul_22_8_n_146));
  NAND2BX1 mul_22_8_g2256(.AN (mul_22_8_n_141), .B (mul_22_8_n_142), .Y
       (mul_22_8_n_144));
  XNOR2X1 mul_22_8_g2257(.A (mul_22_8_n_112), .B (mul_22_8_n_135), .Y
       (mul_22_8_n_143));
  NAND2X1 mul_22_8_g2258(.A (mul_22_8_n_119), .B (mul_22_8_n_138), .Y
       (mul_22_8_n_142));
  NOR2X1 mul_22_8_g2259(.A (mul_22_8_n_119), .B (mul_22_8_n_138), .Y
       (mul_22_8_n_141));
  ADDFX1 mul_22_8_g2260(.A (mul_22_8_n_113), .B (mul_22_8_n_103), .CI
       (mul_22_8_n_93), .CO (mul_22_8_n_139), .S (mul_22_8_n_140));
  ADDFX1 mul_22_8_g2261(.A (mul_22_8_n_118), .B (mul_22_8_n_75), .CI
       (mul_22_8_n_95), .CO (mul_22_8_n_137), .S (mul_22_8_n_138));
  NAND2BX1 mul_22_8_g2262(.AN (mul_22_8_n_125), .B (mul_22_8_n_126), .Y
       (mul_22_8_n_136));
  XNOR2X1 mul_22_8_g2263(.A (mul_22_8_n_111), .B (mul_22_8_n_121), .Y
       (mul_22_8_n_135));
  ADDFX1 mul_22_8_g2264(.A (mul_22_8_n_108), .B (mul_22_8_n_90), .CI
       (mul_22_8_n_66), .CO (mul_22_8_n_133), .S (out1[2]));
  ADDFX1 mul_22_8_g2265(.A (mul_22_8_n_87), .B (mul_22_8_n_78), .CI
       (mul_22_8_n_14), .CO (mul_22_8_n_131), .S (mul_22_8_n_132));
  ADDFX1 mul_22_8_g2266(.A (mul_22_8_n_98), .B (mul_22_8_n_77), .CI
       (mul_22_8_n_96), .CO (mul_22_8_n_129), .S (mul_22_8_n_130));
  ADDFX1 mul_22_8_g2267(.A (mul_22_8_n_99), .B (mul_22_8_n_16), .CI
       (mul_22_8_n_84), .CO (mul_22_8_n_127), .S (mul_22_8_n_128));
  NAND2X1 mul_22_8_g2268(.A (mul_22_8_n_116), .B (mul_22_8_n_120), .Y
       (mul_22_8_n_126));
  NOR2X1 mul_22_8_g2269(.A (mul_22_8_n_116), .B (mul_22_8_n_120), .Y
       (mul_22_8_n_125));
  ADDFX1 mul_22_8_g2270(.A (mul_22_8_n_88), .B (mul_22_8_n_72), .CI
       (mul_22_8_n_94), .CO (mul_22_8_n_123), .S (mul_22_8_n_124));
  ADDFX1 mul_22_8_g2271(.A (mul_22_8_n_85), .B (mul_22_8_n_73), .CI
       (mul_22_8_n_17), .CO (mul_22_8_n_121), .S (mul_22_8_n_122));
  ADDFX1 mul_22_8_g2272(.A (mul_22_8_n_80), .B (mul_22_8_n_83), .CI
       (mul_22_8_n_71), .CO (mul_22_8_n_119), .S (mul_22_8_n_120));
  ADDHX1 mul_22_8_g2273(.A (mul_22_8_n_106), .B (mul_22_8_n_86), .CO
       (mul_22_8_n_117), .S (mul_22_8_n_118));
  ADDHX1 mul_22_8_g2274(.A (mul_22_8_n_97), .B (mul_22_8_n_79), .CO
       (mul_22_8_n_116), .S (mul_22_8_n_115));
  ADDHX1 mul_22_8_g2275(.A (mul_22_8_n_105), .B (mul_22_8_n_81), .CO
       (mul_22_8_n_113), .S (mul_22_8_n_114));
  XNOR2X1 mul_22_8_g2276(.A (mul_22_8_n_18), .B (mul_22_8_n_109), .Y
       (mul_22_8_n_112));
  XNOR2X1 mul_22_8_g2277(.A (mul_22_8_n_107), .B (mul_22_8_n_100), .Y
       (mul_22_8_n_111));
  AOI21XL mul_22_8_g2278(.A0 (mul_22_8_n_59), .A1 (mul_22_8_n_92), .B0
       (mul_22_8_n_108), .Y (out1[1]));
  XNOR2X1 mul_22_8_g2279(.A (mul_22_8_n_82), .B (mul_22_8_n_89), .Y
       (mul_22_8_n_109));
  OAI22X1 mul_22_8_g2280(.A0 (mul_22_8_n_56), .A1 (mul_22_8_n_69), .B0
       (mul_22_8_n_44), .B1 (mul_22_8_n_25), .Y (mul_22_8_n_107));
  AOI221X1 mul_22_8_g2281(.A0 (in1[4]), .A1 (in1[3]), .B0 (in2[0]), .B1
       (mul_22_8_n_1), .C0 (mul_22_8_n_3), .Y (mul_22_8_n_106));
  AOI221X1 mul_22_8_g2282(.A0 (in1[6]), .A1 (in1[5]), .B0 (in2[0]), .B1
       (mul_22_8_n_0), .C0 (mul_22_8_n_4), .Y (mul_22_8_n_105));
  OAI22X1 mul_22_8_g2283(.A0 (mul_22_8_n_30), .A1 (mul_22_8_n_70), .B0
       (mul_22_8_n_31), .B1 (mul_22_8_n_26), .Y (mul_22_8_n_104));
  OAI22X1 mul_22_8_g2284(.A0 (mul_22_8_n_32), .A1 (mul_22_8_n_70), .B0
       (mul_22_8_n_30), .B1 (mul_22_8_n_26), .Y (mul_22_8_n_103));
  NOR2X1 mul_22_8_g2285(.A (mul_22_8_n_59), .B (mul_22_8_n_92), .Y
       (mul_22_8_n_108));
  OAI22X1 mul_22_8_g2286(.A0 (mul_22_8_n_31), .A1 (mul_22_8_n_70), .B0
       (mul_22_8_n_38), .B1 (mul_22_8_n_26), .Y (mul_22_8_n_102));
  OAI22X1 mul_22_8_g2287(.A0 (mul_22_8_n_58), .A1 (mul_22_8_n_69), .B0
       (mul_22_8_n_56), .B1 (mul_22_8_n_25), .Y (mul_22_8_n_101));
  OAI22X1 mul_22_8_g2288(.A0 (mul_22_8_n_38), .A1 (mul_22_8_n_70), .B0
       (mul_22_8_n_23), .B1 (mul_22_8_n_26), .Y (mul_22_8_n_100));
  OAI22X1 mul_22_8_g2289(.A0 (mul_22_8_n_36), .A1 (mul_22_8_n_69), .B0
       (mul_22_8_n_58), .B1 (mul_22_8_n_25), .Y (mul_22_8_n_99));
  OAI22X1 mul_22_8_g2290(.A0 (mul_22_8_n_37), .A1 (mul_22_8_n_69), .B0
       (mul_22_8_n_35), .B1 (mul_22_8_n_25), .Y (mul_22_8_n_98));
  AOI221X1 mul_22_8_g2291(.A0 (in2[0]), .A1 (in1[1]), .B0 (in1[2]), .B1
       (mul_22_8_n_13), .C0 (mul_22_8_n_2), .Y (mul_22_8_n_97));
  OAI22X1 mul_22_8_g2292(.A0 (mul_22_8_n_24), .A1 (mul_22_8_n_70), .B0
       (mul_22_8_n_32), .B1 (mul_22_8_n_26), .Y (mul_22_8_n_96));
  OAI22X1 mul_22_8_g2293(.A0 (mul_22_8_n_22), .A1 (mul_22_8_n_69), .B0
       (mul_22_8_n_40), .B1 (mul_22_8_n_25), .Y (mul_22_8_n_95));
  OAI22X1 mul_22_8_g2294(.A0 (mul_22_8_n_40), .A1 (mul_22_8_n_69), .B0
       (mul_22_8_n_37), .B1 (mul_22_8_n_25), .Y (mul_22_8_n_94));
  OAI22X1 mul_22_8_g2295(.A0 (mul_22_8_n_35), .A1 (mul_22_8_n_69), .B0
       (mul_22_8_n_36), .B1 (mul_22_8_n_25), .Y (mul_22_8_n_93));
  OAI22X1 mul_22_8_g2296(.A0 (mul_22_8_n_39), .A1 (mul_22_8_n_68), .B0
       (mul_22_8_n_9), .B1 (mul_22_8_n_29), .Y (mul_22_8_n_91));
  OAI22X1 mul_22_8_g2297(.A0 (mul_22_8_n_34), .A1 (mul_22_8_n_68), .B0
       (mul_22_8_n_9), .B1 (mul_22_8_n_39), .Y (mul_22_8_n_90));
  AOI22X1 mul_22_8_g2298(.A0 (mul_22_8_n_20), .A1 (mul_22_8_n_67), .B0
       (in1[0]), .B1 (mul_22_8_n_33), .Y (mul_22_8_n_92));
  OAI22X1 mul_22_8_g2299(.A0 (mul_22_8_n_62), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_46), .B1 (mul_22_8_n_48), .Y (mul_22_8_n_89));
  OAI22X1 mul_22_8_g2300(.A0 (mul_22_8_n_52), .A1 (mul_22_8_n_68), .B0
       (mul_22_8_n_9), .B1 (mul_22_8_n_57), .Y (mul_22_8_n_88));
  OAI22X1 mul_22_8_g2301(.A0 (mul_22_8_n_49), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_53), .B1 (mul_22_8_n_48), .Y (mul_22_8_n_87));
  OAI22X1 mul_22_8_g2302(.A0 (mul_22_8_n_51), .A1 (mul_22_8_n_68), .B0
       (mul_22_8_n_9), .B1 (mul_22_8_n_52), .Y (mul_22_8_n_86));
  OAI22X1 mul_22_8_g2303(.A0 (mul_22_8_n_60), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_62), .B1 (mul_22_8_n_48), .Y (mul_22_8_n_85));
  OAI22X1 mul_22_8_g2304(.A0 (mul_22_8_n_53), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_60), .B1 (mul_22_8_n_48), .Y (mul_22_8_n_84));
  OAI22X1 mul_22_8_g2305(.A0 (mul_22_8_n_29), .A1 (mul_22_8_n_68), .B0
       (mul_22_8_n_9), .B1 (mul_22_8_n_51), .Y (mul_22_8_n_83));
  AOI22X1 mul_22_8_g2306(.A0 (mul_22_8_n_55), .A1 (mul_22_8_n_67), .B0
       (in1[0]), .B1 (mul_22_8_n_47), .Y (mul_22_8_n_82));
  OAI22X1 mul_22_8_g2307(.A0 (mul_22_8_n_57), .A1 (mul_22_8_n_68), .B0
       (mul_22_8_n_9), .B1 (mul_22_8_n_61), .Y (mul_22_8_n_81));
  OAI22X1 mul_22_8_g2308(.A0 (mul_22_8_n_41), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_27), .B1 (mul_22_8_n_48), .Y (mul_22_8_n_80));
  OAI22X1 mul_22_8_g2309(.A0 (mul_22_8_n_19), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_41), .B1 (mul_22_8_n_48), .Y (mul_22_8_n_79));
  OAI22X1 mul_22_8_g2310(.A0 (mul_22_8_n_61), .A1 (mul_22_8_n_68), .B0
       (mul_22_8_n_9), .B1 (mul_22_8_n_63), .Y (mul_22_8_n_78));
  OAI22X1 mul_22_8_g2311(.A0 (mul_22_8_n_50), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_49), .B1 (mul_22_8_n_48), .Y (mul_22_8_n_77));
  OAI22X1 mul_22_8_g2312(.A0 (mul_22_8_n_28), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_50), .B1 (mul_22_8_n_48), .Y (mul_22_8_n_76));
  OAI22X1 mul_22_8_g2313(.A0 (mul_22_8_n_27), .A1 (mul_22_8_n_65), .B0
       (mul_22_8_n_28), .B1 (mul_22_8_n_48), .Y (mul_22_8_n_75));
  OAI22X1 mul_22_8_g2314(.A0 (mul_22_8_n_63), .A1 (mul_22_8_n_68), .B0
       (mul_22_8_n_9), .B1 (mul_22_8_n_64), .Y (mul_22_8_n_74));
  OAI22X1 mul_22_8_g2315(.A0 (mul_22_8_n_64), .A1 (mul_22_8_n_68), .B0
       (mul_22_8_n_9), .B1 (mul_22_8_n_54), .Y (mul_22_8_n_73));
  NOR2X1 mul_22_8_g2316(.A (mul_22_8_n_5), .B (mul_22_8_n_26), .Y
       (mul_22_8_n_72));
  NOR2X1 mul_22_8_g2317(.A (mul_22_8_n_5), .B (mul_22_8_n_25), .Y
       (mul_22_8_n_71));
  NAND2X1 mul_22_8_g2318(.A (mul_22_8_n_42), .B (mul_22_8_n_26), .Y
       (mul_22_8_n_70));
  NAND2X1 mul_22_8_g2319(.A (mul_22_8_n_43), .B (mul_22_8_n_25), .Y
       (mul_22_8_n_69));
  INVX1 mul_22_8_g2320(.A (mul_22_8_n_68), .Y (mul_22_8_n_67));
  NAND2X1 mul_22_8_g2321(.A (mul_22_8_n_9), .B (mul_22_8_n_21), .Y
       (mul_22_8_n_68));
  NOR2X1 mul_22_8_g2322(.A (mul_22_8_n_5), .B (mul_22_8_n_48), .Y
       (mul_22_8_n_66));
  NAND2X1 mul_22_8_g2323(.A (mul_22_8_n_45), .B (mul_22_8_n_48), .Y
       (mul_22_8_n_65));
  INVX1 mul_22_8_g2324(.A (mul_22_8_n_54), .Y (mul_22_8_n_55));
  MXI2XL mul_22_8_g2325(.A (mul_22_8_n_8), .B (in1[1]), .S0 (in2[11]),
       .Y (mul_22_8_n_47));
  MXI2XL mul_22_8_g2326(.A (in1[3]), .B (mul_22_8_n_2), .S0 (in2[9]),
       .Y (mul_22_8_n_46));
  MXI2XL mul_22_8_g2327(.A (mul_22_8_n_2), .B (in1[3]), .S0 (in1[2]),
       .Y (mul_22_8_n_45));
  MXI2XL mul_22_8_g2328(.A (in1[5]), .B (mul_22_8_n_3), .S0 (in2[7]),
       .Y (mul_22_8_n_44));
  MXI2XL mul_22_8_g2329(.A (mul_22_8_n_3), .B (in1[5]), .S0 (in1[4]),
       .Y (mul_22_8_n_43));
  MXI2XL mul_22_8_g2330(.A (mul_22_8_n_4), .B (in1[7]), .S0 (in1[6]),
       .Y (mul_22_8_n_42));
  XNOR2X1 mul_22_8_g2331(.A (in2[9]), .B (in1[1]), .Y (mul_22_8_n_64));
  XNOR2X1 mul_22_8_g2332(.A (in2[8]), .B (in1[1]), .Y (mul_22_8_n_63));
  MXI2XL mul_22_8_g2333(.A (in1[3]), .B (mul_22_8_n_2), .S0 (in2[8]),
       .Y (mul_22_8_n_62));
  XNOR2X1 mul_22_8_g2334(.A (in2[7]), .B (in1[1]), .Y (mul_22_8_n_61));
  MXI2XL mul_22_8_g2335(.A (in1[3]), .B (mul_22_8_n_2), .S0 (in2[7]),
       .Y (mul_22_8_n_60));
  NAND2BX1 mul_22_8_g2336(.AN (out1[0]), .B (in1[1]), .Y
       (mul_22_8_n_59));
  AOI22X1 mul_22_8_g2337(.A0 (in2[5]), .A1 (mul_22_8_n_3), .B0
       (in1[5]), .B1 (mul_22_8_n_7), .Y (mul_22_8_n_58));
  XNOR2X1 mul_22_8_g2338(.A (in2[6]), .B (in1[1]), .Y (mul_22_8_n_57));
  MXI2XL mul_22_8_g2339(.A (in1[5]), .B (mul_22_8_n_3), .S0 (in2[6]),
       .Y (mul_22_8_n_56));
  XNOR2X1 mul_22_8_g2340(.A (in2[10]), .B (in1[1]), .Y (mul_22_8_n_54));
  MX2XL mul_22_8_g2341(.A (mul_22_8_n_2), .B (in1[3]), .S0 (in2[6]), .Y
       (mul_22_8_n_53));
  XNOR2X1 mul_22_8_g2342(.A (in2[5]), .B (in1[1]), .Y (mul_22_8_n_52));
  XNOR2X1 mul_22_8_g2343(.A (in2[4]), .B (in1[1]), .Y (mul_22_8_n_51));
  AOI22X1 mul_22_8_g2344(.A0 (in2[4]), .A1 (mul_22_8_n_2), .B0
       (in1[3]), .B1 (mul_22_8_n_12), .Y (mul_22_8_n_50));
  AOI22X1 mul_22_8_g2345(.A0 (in2[5]), .A1 (mul_22_8_n_2), .B0
       (in1[3]), .B1 (mul_22_8_n_7), .Y (mul_22_8_n_49));
  XNOR2X1 mul_22_8_g2346(.A (in1[2]), .B (in1[1]), .Y (mul_22_8_n_48));
  INVX1 mul_22_8_g2347(.A (mul_22_8_n_33), .Y (mul_22_8_n_34));
  AOI22X1 mul_22_8_g2348(.A0 (in2[0]), .A1 (mul_22_8_n_4), .B0
       (in1[7]), .B1 (mul_22_8_n_5), .Y (mul_22_8_n_24));
  AOI22X1 mul_22_8_g2349(.A0 (in2[5]), .A1 (mul_22_8_n_4), .B0
       (in1[7]), .B1 (mul_22_8_n_7), .Y (mul_22_8_n_23));
  AOI22X1 mul_22_8_g2350(.A0 (in2[0]), .A1 (mul_22_8_n_3), .B0
       (in1[5]), .B1 (mul_22_8_n_5), .Y (mul_22_8_n_22));
  OAI22X1 mul_22_8_g2351(.A0 (mul_22_8_n_8), .A1 (in1[0]), .B0
       (mul_22_8_n_9), .B1 (in1[1]), .Y (mul_22_8_n_21));
  OAI22X1 mul_22_8_g2352(.A0 (mul_22_8_n_5), .A1 (in1[1]), .B0
       (mul_22_8_n_8), .B1 (in2[0]), .Y (mul_22_8_n_20));
  AOI22X1 mul_22_8_g2353(.A0 (in2[0]), .A1 (mul_22_8_n_2), .B0
       (in1[3]), .B1 (mul_22_8_n_5), .Y (mul_22_8_n_19));
  AOI22X1 mul_22_8_g2354(.A0 (in2[1]), .A1 (mul_22_8_n_2), .B0
       (in1[3]), .B1 (mul_22_8_n_6), .Y (mul_22_8_n_41));
  AOI22X1 mul_22_8_g2355(.A0 (in2[1]), .A1 (mul_22_8_n_3), .B0
       (in1[5]), .B1 (mul_22_8_n_6), .Y (mul_22_8_n_40));
  AOI22X1 mul_22_8_g2356(.A0 (in2[2]), .A1 (mul_22_8_n_8), .B0
       (in1[1]), .B1 (mul_22_8_n_11), .Y (mul_22_8_n_39));
  AOI22X1 mul_22_8_g2357(.A0 (in2[4]), .A1 (mul_22_8_n_4), .B0
       (in1[7]), .B1 (mul_22_8_n_12), .Y (mul_22_8_n_38));
  AOI22X1 mul_22_8_g2358(.A0 (in2[2]), .A1 (mul_22_8_n_3), .B0
       (in1[5]), .B1 (mul_22_8_n_11), .Y (mul_22_8_n_37));
  AOI22X1 mul_22_8_g2359(.A0 (in2[4]), .A1 (mul_22_8_n_3), .B0
       (in1[5]), .B1 (mul_22_8_n_12), .Y (mul_22_8_n_36));
  AOI22X1 mul_22_8_g2360(.A0 (in2[3]), .A1 (mul_22_8_n_3), .B0
       (in1[5]), .B1 (mul_22_8_n_10), .Y (mul_22_8_n_35));
  OAI22X1 mul_22_8_g2361(.A0 (mul_22_8_n_6), .A1 (in1[1]), .B0
       (mul_22_8_n_8), .B1 (in2[1]), .Y (mul_22_8_n_33));
  AOI22X1 mul_22_8_g2362(.A0 (in2[1]), .A1 (mul_22_8_n_4), .B0
       (in1[7]), .B1 (mul_22_8_n_6), .Y (mul_22_8_n_32));
  AOI22X1 mul_22_8_g2363(.A0 (in2[3]), .A1 (mul_22_8_n_4), .B0
       (in1[7]), .B1 (mul_22_8_n_10), .Y (mul_22_8_n_31));
  AOI22X1 mul_22_8_g2364(.A0 (in2[2]), .A1 (mul_22_8_n_4), .B0
       (in1[7]), .B1 (mul_22_8_n_11), .Y (mul_22_8_n_30));
  AOI22X1 mul_22_8_g2365(.A0 (in2[3]), .A1 (mul_22_8_n_8), .B0
       (in1[1]), .B1 (mul_22_8_n_10), .Y (mul_22_8_n_29));
  AOI22X1 mul_22_8_g2366(.A0 (in2[3]), .A1 (mul_22_8_n_2), .B0
       (in1[3]), .B1 (mul_22_8_n_10), .Y (mul_22_8_n_28));
  AOI22X1 mul_22_8_g2367(.A0 (in2[2]), .A1 (mul_22_8_n_2), .B0
       (in1[3]), .B1 (mul_22_8_n_11), .Y (mul_22_8_n_27));
  MX2X1 mul_22_8_g2368(.A (mul_22_8_n_3), .B (in1[5]), .S0 (in1[6]), .Y
       (mul_22_8_n_26));
  MX2X1 mul_22_8_g2369(.A (mul_22_8_n_2), .B (in1[3]), .S0 (in1[4]), .Y
       (mul_22_8_n_25));
  NAND2X1 mul_22_8_g2372(.A (in2[3]), .B (in1[7]), .Y (mul_22_8_n_18));
  NOR2X1 mul_22_8_g2373(.A (mul_22_8_n_11), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_17));
  NOR2X1 mul_22_8_g2374(.A (mul_22_8_n_6), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_16));
  NOR2X1 mul_22_8_g2375(.A (mul_22_8_n_5), .B (mul_22_8_n_9), .Y
       (out1[0]));
  NOR2X1 mul_22_8_g2376(.A (mul_22_8_n_5), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_14));
  NAND2X1 mul_22_8_g2377(.A (mul_22_8_n_5), .B (mul_22_8_n_8), .Y
       (mul_22_8_n_13));
  INVX1 mul_22_8_g2379(.A (in2[4]), .Y (mul_22_8_n_12));
  INVX1 mul_22_8_g2380(.A (in2[2]), .Y (mul_22_8_n_11));
  INVX1 mul_22_8_g2381(.A (in2[3]), .Y (mul_22_8_n_10));
  INVX1 mul_22_8_g2382(.A (in1[0]), .Y (mul_22_8_n_9));
  INVX1 mul_22_8_g2383(.A (in1[1]), .Y (mul_22_8_n_8));
  INVX1 mul_22_8_g2385(.A (in2[5]), .Y (mul_22_8_n_7));
  INVX1 mul_22_8_g2386(.A (in2[1]), .Y (mul_22_8_n_6));
  INVX1 mul_22_8_g2387(.A (in2[0]), .Y (mul_22_8_n_5));
  INVX1 mul_22_8_g2388(.A (in1[7]), .Y (mul_22_8_n_4));
  INVX1 mul_22_8_g2389(.A (in1[5]), .Y (mul_22_8_n_3));
  INVX1 mul_22_8_g2390(.A (in1[3]), .Y (mul_22_8_n_2));
  NAND2BX1 mul_22_8_g2(.AN (in1[4]), .B (mul_22_8_n_2), .Y
       (mul_22_8_n_1));
  NAND2BX1 mul_22_8_g2391(.AN (in1[6]), .B (mul_22_8_n_3), .Y
       (mul_22_8_n_0));
endmodule

