// Generated by stratus_hls 19.12-s100  (91710.131054)
// Mon Apr 26 12:58:10 2021
// from ../SobelFilter.cpp
#include "SobelFilter_rtl.h"

struct SobelFilter;
SobelFilter::SobelFilter(sc_module_name name) : sc_module(name) 
    ,i_clk("i_clk")
    ,i_rst("i_rst")
    ,i_r_busy("i_r_busy")
    ,i_r_vld("i_r_vld")
    ,i_r_data("i_r_data")
    ,i_g_busy("i_g_busy")
    ,i_g_vld("i_g_vld")
    ,i_g_data("i_g_data")
    ,i_b_busy("i_b_busy")
    ,i_b_vld("i_b_vld")
    ,i_b_data("i_b_data")
    ,o_result_r_busy("o_result_r_busy")
    ,o_result_r_vld("o_result_r_vld")
    ,o_result_r_data("o_result_r_data")
    ,o_result_g_busy("o_result_g_busy")
    ,o_result_g_vld("o_result_g_vld")
    ,o_result_g_data("o_result_g_data")
    ,o_result_b_busy("o_result_b_busy")
    ,o_result_b_vld("o_result_b_vld")
    ,o_result_b_data("o_result_b_data")
    ,o_result_b_m_req_m_prev_trig_req("o_result_b_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1Ux1U_1U_1_7_out1("SobelFilter_Xor_1Ux1U_1U_1_7_out1")
    ,o_result_b_m_unacked_req("o_result_b_m_unacked_req")
    ,SobelFilter_Or_1Ux1U_1U_4_8_out1("SobelFilter_Or_1Ux1U_1U_4_8_out1")
    ,o_result_g_m_req_m_prev_trig_req("o_result_g_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1Ux1U_1U_1_4_out1("SobelFilter_Xor_1Ux1U_1U_1_4_out1")
    ,o_result_g_m_unacked_req("o_result_g_m_unacked_req")
    ,SobelFilter_Or_1Ux1U_1U_4_5_out1("SobelFilter_Or_1Ux1U_1U_4_5_out1")
    ,o_result_r_m_req_m_prev_trig_req("o_result_r_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1Ux1U_1U_1_1_out1("SobelFilter_Xor_1Ux1U_1U_1_1_out1")
    ,o_result_r_m_unacked_req("o_result_r_m_unacked_req")
    ,SobelFilter_Or_1Ux1U_1U_4_2_out1("SobelFilter_Or_1Ux1U_1U_4_2_out1")
    ,SobelFilter_N_Muxb_1_2_11_4_16_out1("SobelFilter_N_Muxb_1_2_11_4_16_out1")
    ,i_b_m_unvalidated_req("i_b_m_unvalidated_req")
    ,SobelFilter_gen_busy_r_4_32_gen_busy_0_i_r_m_data_is_invalid_next("SobelFilter_gen_busy_r_4_32_gen_busy_0_i_r_m_data_is_invalid_next")
    ,SobelFilter_gen_busy_r_4_32_gdiv_i3("SobelFilter_gen_busy_r_4_32_gdiv_i3")
    ,SobelFilter_gen_busy_r_4_32_gnew_req_i1("SobelFilter_gen_busy_r_4_32_gnew_req_i1")
    ,SobelFilter_N_Muxb_1_2_11_4_13_out1("SobelFilter_N_Muxb_1_2_11_4_13_out1")
    ,i_g_m_unvalidated_req("i_g_m_unvalidated_req")
    ,SobelFilter_gen_busy_r_4_31_gen_busy_0_i_r_m_data_is_invalid_next("SobelFilter_gen_busy_r_4_31_gen_busy_0_i_r_m_data_is_invalid_next")
    ,SobelFilter_gen_busy_r_4_31_gdiv_i3("SobelFilter_gen_busy_r_4_31_gdiv_i3")
    ,SobelFilter_gen_busy_r_4_31_gnew_req_i1("SobelFilter_gen_busy_r_4_31_gnew_req_i1")
    ,SobelFilter_N_Muxb_1_2_11_4_10_out1("SobelFilter_N_Muxb_1_2_11_4_10_out1")
    ,i_r_m_unvalidated_req("i_r_m_unvalidated_req")
    ,SobelFilter_gen_busy_r_4_30_gen_busy_0_i_r_m_data_is_invalid_next("SobelFilter_gen_busy_r_4_30_gen_busy_0_i_r_m_data_is_invalid_next")
    ,SobelFilter_gen_busy_r_4_30_gdiv_i3("SobelFilter_gen_busy_r_4_30_gdiv_i3")
    ,SobelFilter_gen_busy_r_4_30_gnew_req_i1("SobelFilter_gen_busy_r_4_30_gnew_req_i1")
    ,global_state_next("global_state_next")
    ,SobelFilter_Add2Mul2s12u8u12_4_21_in1("SobelFilter_Add2Mul2s12u8u12_4_21_in1")
    ,SobelFilter_Add2Mul2s12u8u12_4_21_in2("SobelFilter_Add2Mul2s12u8u12_4_21_in2")
    ,SobelFilter_Add2Mul2s12u8u12_4_21_in3("SobelFilter_Add2Mul2s12u8u12_4_21_in3")
    ,gs_ctrl0("gs_ctrl0")
    ,SobelFilter_Add2u2Mul2i3u2_4_18_out1("SobelFilter_Add2u2Mul2i3u2_4_18_out1")
    ,s_reg_25("s_reg_25")
    ,SobelFilter_Add2i1u2_4_19_out1("SobelFilter_Add2i1u2_4_19_out1")
    ,SobelFilter_Add2i1u2_4_20_out1("SobelFilter_Add2i1u2_4_20_out1")
    ,s_reg_23("s_reg_23")
    ,SobelFilter_Add2Mul2s12u8u12_4_21_out1("SobelFilter_Add2Mul2s12u8u12_4_21_out1")
    ,SobelFilter_Add2Mul2s12u8u12_4_25_out1("SobelFilter_Add2Mul2s12u8u12_4_25_out1")
    ,s_reg_24("s_reg_24")
    ,s_reg_19("s_reg_19")
    ,SobelFilter_gen_busy_r_4_30_out1("SobelFilter_gen_busy_r_4_30_out1")
    ,SobelFilter_gen_busy_r_4_31_out1("SobelFilter_gen_busy_r_4_31_out1")
    ,SobelFilter_gen_busy_r_4_32_out1("SobelFilter_gen_busy_r_4_32_out1")
    ,SobelFilter_And_1Ux1U_1U_4_26_out1("SobelFilter_And_1Ux1U_1U_4_26_out1")
    ,SobelFilter_And_1Ux1U_1U_4_27_out1("SobelFilter_And_1Ux1U_1U_4_27_out1")
    ,SobelFilter_And_1Ux1U_1U_4_28_out1("SobelFilter_And_1Ux1U_1U_4_28_out1")
    ,SobelFilter_Not_1U_1U_1_9_out1("SobelFilter_Not_1U_1U_1_9_out1")
    ,o_result_b_m_req_m_trig_req("o_result_b_m_req_m_trig_req")
    ,SobelFilter_Not_1U_1U_1_6_out1("SobelFilter_Not_1U_1U_1_6_out1")
    ,o_result_g_m_req_m_trig_req("o_result_g_m_req_m_trig_req")
    ,SobelFilter_Not_1U_1U_1_3_out1("SobelFilter_Not_1U_1U_1_3_out1")
    ,o_result_r_m_req_m_trig_req("o_result_r_m_req_m_trig_req")
    ,i_b_m_busy_req_0("i_b_m_busy_req_0")
    ,i_g_m_busy_req_0("i_g_m_busy_req_0")
    ,i_r_m_busy_req_0("i_r_m_busy_req_0")
    ,s_reg_22("s_reg_22")
    ,SobelFilter_Lti3u2_4_23_out1("SobelFilter_Lti3u2_4_23_out1")
    ,SobelFilter_Lti3u2_4_22_out1("SobelFilter_Lti3u2_4_22_out1")
    ,s_reg_21("s_reg_21")
    ,s_reg_20("s_reg_20")
    ,global_state("global_state")
    ,stall0("stall0")
    ,filter_in1("filter_in1")
    ,filter_out1("filter_out1")
{
  filter = new SobelFilter_ROM_9X32_filter("filter");
  filter->in1(filter_in1);
  filter->out1(filter_out1);
  filter->clk(i_clk);

  SC_METHOD(drive_o_result_b_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_g_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_r_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_r_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_g_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_b_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_r_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_g_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_result_b_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_stall0);
  sensitive << ( global_state );
  sensitive << ( SobelFilter_gen_busy_r_4_30_out1 );
  sensitive << ( SobelFilter_gen_busy_r_4_31_out1 );
  sensitive << ( SobelFilter_gen_busy_r_4_32_out1 );
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_26_out1 );
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_27_out1 );
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_28_out1 );

  SC_METHOD(drive_s_reg_19);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_20);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_21);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_22);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_23);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_24);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_25);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Add2u2Mul2i3u2_4_18);
  sensitive << ( s_reg_23 );
  sensitive << ( s_reg_19 );

  SC_METHOD(SobelFilter_Add2i1u2_4_19);
  sensitive << ( s_reg_19 );

  SC_METHOD(SobelFilter_Add2i1u2_4_20);
  sensitive << ( s_reg_23 );

  SC_METHOD(drive_filter_in1);
  sensitive << ( SobelFilter_Add2u2Mul2i3u2_4_18_out1 );

  SC_METHOD(drive_SobelFilter_Add2Mul2s12u8u12_4_21_in3);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_21 );
  sensitive << ( s_reg_22 );

  SC_METHOD(drive_SobelFilter_Add2Mul2s12u8u12_4_21_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( o_result_g_data );
  sensitive << ( o_result_r_data );

  SC_METHOD(drive_SobelFilter_Add2Mul2s12u8u12_4_21_in1);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_25 );
  sensitive << ( filter_out1 );

  SC_METHOD(SobelFilter_Add2Mul2s12u8u12_4_21);
  sensitive << ( SobelFilter_Add2Mul2s12u8u12_4_21_in1 );
  sensitive << ( SobelFilter_Add2Mul2s12u8u12_4_21_in2 );
  sensitive << ( SobelFilter_Add2Mul2s12u8u12_4_21_in3 );

  SC_METHOD(SobelFilter_Lti3u2_4_22);
  sensitive << ( s_reg_24 );

  SC_METHOD(SobelFilter_Lti3u2_4_23);
  sensitive << ( s_reg_23 );

  SC_METHOD(SobelFilter_Add2Mul2s12u8u12_4_25);
  sensitive << ( s_reg_25 );
  sensitive << ( o_result_b_data );
  sensitive << ( s_reg_20 );

  SC_METHOD(drive_global_state);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_global_state_next);
  sensitive << ( global_state );
  sensitive << ( SobelFilter_Lti3u2_4_23_out1 );
  sensitive << ( SobelFilter_Lti3u2_4_22_out1 );

  SC_METHOD(drive_gs_ctrl0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_r_busy);
  sensitive << ( SobelFilter_gen_busy_r_4_30_out1 );

  SC_METHOD(SobelFilter_gen_busy_r_4_30_p8);
  sensitive << ( 
  SobelFilter_gen_busy_r_4_30_gen_busy_0_i_r_m_data_is_invalid_next );
  sensitive << ( SobelFilter_gen_busy_r_4_30_gdiv_i3 );
  sensitive << ( SobelFilter_gen_busy_r_4_30_gnew_req_i1 );

  SC_METHOD(SobelFilter_gen_busy_r_4_30_p7);
  sensitive << ( SobelFilter_gen_busy_r_4_30_gdiv_i3 );

  SC_METHOD(SobelFilter_gen_busy_r_4_30_p6);
  sensitive << ( SobelFilter_gen_busy_r_4_30_gnew_req_i1 );
  sensitive << ( i_r_vld );

  SC_METHOD(SobelFilter_gen_busy_r_4_30_p5);
  sensitive << ( i_r_vld );
  sensitive << ( i_r_m_unvalidated_req );
  sensitive << ( i_r_m_busy_req_0 );

  SC_METHOD(drive_i_r_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_N_Muxb_1_2_11_4_10);
  sensitive << ( i_r_m_busy_req_0 );
  sensitive << ( i_r_m_unvalidated_req );
  sensitive << ( i_r_vld );

  SC_METHOD(drive_i_g_busy);
  sensitive << ( SobelFilter_gen_busy_r_4_31_out1 );

  SC_METHOD(SobelFilter_gen_busy_r_4_31_p8);
  sensitive << ( 
  SobelFilter_gen_busy_r_4_31_gen_busy_0_i_r_m_data_is_invalid_next );
  sensitive << ( SobelFilter_gen_busy_r_4_31_gdiv_i3 );
  sensitive << ( SobelFilter_gen_busy_r_4_31_gnew_req_i1 );

  SC_METHOD(SobelFilter_gen_busy_r_4_31_p7);
  sensitive << ( SobelFilter_gen_busy_r_4_31_gdiv_i3 );

  SC_METHOD(SobelFilter_gen_busy_r_4_31_p6);
  sensitive << ( SobelFilter_gen_busy_r_4_31_gnew_req_i1 );
  sensitive << ( i_g_vld );

  SC_METHOD(SobelFilter_gen_busy_r_4_31_p5);
  sensitive << ( i_g_vld );
  sensitive << ( i_g_m_unvalidated_req );
  sensitive << ( i_g_m_busy_req_0 );

  SC_METHOD(drive_i_g_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_N_Muxb_1_2_11_4_13);
  sensitive << ( i_g_m_busy_req_0 );
  sensitive << ( i_g_m_unvalidated_req );
  sensitive << ( i_g_vld );

  SC_METHOD(drive_i_b_busy);
  sensitive << ( SobelFilter_gen_busy_r_4_32_out1 );

  SC_METHOD(SobelFilter_gen_busy_r_4_32_p8);
  sensitive << ( 
  SobelFilter_gen_busy_r_4_32_gen_busy_0_i_r_m_data_is_invalid_next );
  sensitive << ( SobelFilter_gen_busy_r_4_32_gdiv_i3 );
  sensitive << ( SobelFilter_gen_busy_r_4_32_gnew_req_i1 );

  SC_METHOD(SobelFilter_gen_busy_r_4_32_p7);
  sensitive << ( SobelFilter_gen_busy_r_4_32_gdiv_i3 );

  SC_METHOD(SobelFilter_gen_busy_r_4_32_p6);
  sensitive << ( SobelFilter_gen_busy_r_4_32_gnew_req_i1 );
  sensitive << ( i_b_vld );

  SC_METHOD(SobelFilter_gen_busy_r_4_32_p5);
  sensitive << ( i_b_vld );
  sensitive << ( i_b_m_unvalidated_req );
  sensitive << ( i_b_m_busy_req_0 );

  SC_METHOD(drive_i_b_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_N_Muxb_1_2_11_4_16);
  sensitive << ( i_b_m_busy_req_0 );
  sensitive << ( i_b_m_unvalidated_req );
  sensitive << ( i_b_vld );

  SC_METHOD(drive_o_result_r_vld);
  sensitive << ( SobelFilter_Or_1Ux1U_1U_4_2_out1 );

  SC_METHOD(SobelFilter_Or_1Ux1U_1U_4_2);
  sensitive << ( SobelFilter_Xor_1Ux1U_1U_1_1_out1 );
  sensitive << ( o_result_r_m_unacked_req );

  SC_METHOD(drive_o_result_r_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_26);
  sensitive << ( o_result_r_vld );
  sensitive << ( o_result_r_busy );

  SC_METHOD(SobelFilter_Xor_1Ux1U_1U_1_1);
  sensitive << ( o_result_r_m_req_m_prev_trig_req );
  sensitive << ( o_result_r_m_req_m_trig_req );

  SC_METHOD(drive_o_result_r_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1U_1_3);
  sensitive << ( o_result_r_m_req_m_trig_req );

  SC_METHOD(drive_o_result_g_vld);
  sensitive << ( SobelFilter_Or_1Ux1U_1U_4_5_out1 );

  SC_METHOD(SobelFilter_Or_1Ux1U_1U_4_5);
  sensitive << ( SobelFilter_Xor_1Ux1U_1U_1_4_out1 );
  sensitive << ( o_result_g_m_unacked_req );

  SC_METHOD(drive_o_result_g_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_27);
  sensitive << ( o_result_g_vld );
  sensitive << ( o_result_g_busy );

  SC_METHOD(SobelFilter_Xor_1Ux1U_1U_1_4);
  sensitive << ( o_result_g_m_req_m_prev_trig_req );
  sensitive << ( o_result_g_m_req_m_trig_req );

  SC_METHOD(drive_o_result_g_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1U_1_6);
  sensitive << ( o_result_g_m_req_m_trig_req );

  SC_METHOD(drive_o_result_b_vld);
  sensitive << ( SobelFilter_Or_1Ux1U_1U_4_8_out1 );

  SC_METHOD(SobelFilter_Or_1Ux1U_1U_4_8);
  sensitive << ( SobelFilter_Xor_1Ux1U_1U_1_7_out1 );
  sensitive << ( o_result_b_m_unacked_req );

  SC_METHOD(drive_o_result_b_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_28);
  sensitive << ( o_result_b_vld );
  sensitive << ( o_result_b_busy );

  SC_METHOD(SobelFilter_Xor_1Ux1U_1U_1_7);
  sensitive << ( o_result_b_m_req_m_prev_trig_req );
  sensitive << ( o_result_b_m_req_m_trig_req );

  SC_METHOD(drive_o_result_b_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1U_1_9);
  sensitive << ( o_result_b_m_req_m_trig_req );

}
// resource: mux_8bx2i0c
// resource: regr_en_8
void SobelFilter::drive_o_result_b_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 3ULL: 
      o_result_b_data = i_b_data.read();
      break;
    case 7ULL: 
      o_result_b_data = (sc_uint<8> ) (s_reg_20.read().range(11,4));
      break;
    }
    break;
  }
}
// resource: mux_8bx2i0c
// resource: regr_en_8
void SobelFilter::drive_o_result_g_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 2ULL: 
      o_result_g_data = i_g_data.read();
      break;
    case 6ULL: 
      o_result_g_data = (sc_uint<8> ) (s_reg_21.read().range(11,4));
      break;
    }
    break;
  }
}
// resource: mux_8bx2i0c
// resource: regr_en_8
void SobelFilter::drive_o_result_r_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 1ULL: 
      o_result_r_data = i_r_data.read();
      break;
    case 5ULL: 
      if ( (!SobelFilter_Lti3u2_4_23_out1.read() && !
           SobelFilter_Lti3u2_4_22_out1.read()) ) {
        o_result_r_data = (sc_uint<8> ) (s_reg_22.read().range(11,4));
      } 
      break;
    }
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void SobelFilter::drive_i_r_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_r_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 0ULL: case 9ULL: 
        i_r_m_busy_req_0 = 0ULL;
        break;
      case 1ULL: 
        i_r_m_busy_req_0 = 1ULL;
        break;
      case 5ULL: 
        if ( SobelFilter_Lti3u2_4_23_out1.read() ) {
          i_r_m_busy_req_0 = 0ULL;
        } else {
          if ( SobelFilter_Lti3u2_4_22_out1.read() ) {
            i_r_m_busy_req_0 = 0ULL;
          } 
        }
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void SobelFilter::drive_i_g_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_g_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 1ULL: 
        i_g_m_busy_req_0 = 0ULL;
        break;
      case 2ULL: 
        i_g_m_busy_req_0 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void SobelFilter::drive_i_b_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_b_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 2ULL: 
        i_b_m_busy_req_0 = 0ULL;
        break;
      case 3ULL: 
        i_b_m_busy_req_0 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void SobelFilter::drive_o_result_r_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_r_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 5ULL: 
        if ( (!SobelFilter_Lti3u2_4_23_out1.read() && !
             SobelFilter_Lti3u2_4_22_out1.read()) ) {
          o_result_r_m_req_m_trig_req = (sc_uint<1> ) (
                                        SobelFilter_Not_1U_1U_1_3_out1.read());
        } 
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void SobelFilter::drive_o_result_g_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_g_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 6ULL: 
        o_result_g_m_req_m_trig_req = (sc_uint<1> ) (
                                      SobelFilter_Not_1U_1U_1_6_out1.read());
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void SobelFilter::drive_o_result_b_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_b_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 7ULL: 
        o_result_b_m_req_m_trig_req = (sc_uint<1> ) (
                                      SobelFilter_Not_1U_1U_1_9_out1.read());
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx7i1c
void SobelFilter::drive_stall0(){
  switch( (sc_uint<4>)(global_state.read()) ) {
  default:
    stall0 = 0ULL;
    break;
  case 1ULL: 
    stall0 = (sc_uint<1> )SobelFilter_gen_busy_r_4_30_out1.read();
    break;
  case 2ULL: 
    stall0 = (sc_uint<1> )SobelFilter_gen_busy_r_4_31_out1.read();
    break;
  case 3ULL: 
    stall0 = (sc_uint<1> )SobelFilter_gen_busy_r_4_32_out1.read();
    break;
  case 6ULL: 
    stall0 = SobelFilter_And_1Ux1U_1U_4_26_out1.read();
    break;
  case 7ULL: 
    stall0 = SobelFilter_And_1Ux1U_1U_4_27_out1.read();
    break;
  case 8ULL: 
    stall0 = SobelFilter_And_1Ux1U_1U_4_28_out1.read();
    break;
  }
}
// resource: mux_2bx2i1c
// resource: regr_en_2
void SobelFilter::drive_s_reg_19(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_19 = 0ULL;
      break;
    case 5ULL: 
      if ( SobelFilter_Lti3u2_4_23_out1.read() );
      else {
        s_reg_19 = s_reg_24.read();
      }
      break;
    }
    break;
  }
}
// resource: mux_12bx2i1c
// resource: regr_en_12
void SobelFilter::drive_s_reg_20(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_20 = 0ULL;
      break;
    case 5ULL: 
      s_reg_20 = SobelFilter_Add2Mul2s12u8u12_4_25_out1.read();
      break;
    }
    break;
  }
}
// resource: mux_12bx2i1c
// resource: regr_en_12
void SobelFilter::drive_s_reg_21(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_21 = 0ULL;
      break;
    case 5ULL: 
      s_reg_21 = SobelFilter_Add2Mul2s12u8u12_4_21_out1.read();
      break;
    }
    break;
  }
}
// resource: mux_12bx2i1c
// resource: regr_en_12
void SobelFilter::drive_s_reg_22(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_22 = 0ULL;
      break;
    case 4ULL: 
      s_reg_22 = SobelFilter_Add2Mul2s12u8u12_4_21_out1.read();
      break;
    }
    break;
  }
}
// resource: mux_2bx2i1c
// resource: regr_en_2
void SobelFilter::drive_s_reg_23(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_23 = 0ULL;
      break;
    case 3ULL: 
      s_reg_23 = SobelFilter_Add2i1u2_4_20_out1.read();
      break;
    case 5ULL: 
      if ( SobelFilter_Lti3u2_4_23_out1.read() );
      else {
        s_reg_23 = 0ULL;
      }
      break;
    }
    break;
  }
}
// resource: regr_en_2
void SobelFilter::drive_s_reg_24(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 3ULL: 
      s_reg_24 = SobelFilter_Add2i1u2_4_19_out1.read();
      break;
    }
    break;
  }
}
// resource: regr_en_12
void SobelFilter::drive_s_reg_25(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  case 0ULL: 
    s_reg_25 = (sc_uint<12> )filter_out1.read();
    break;
  }
}
// resource: SobelFilter_Add2u2Mul2i3u2_4  instance: SobelFilter_Add2u2Mul2i3u2_4_18
void SobelFilter::SobelFilter_Add2u2Mul2i3u2_4_18(){
  SobelFilter_Add2u2Mul2i3u2_4_18_out1 = (s_reg_19.read() * 3ULL + s_reg_23
                                         .read());
}
// resource: SobelFilter_Add2i1u2_4  instance: SobelFilter_Add2i1u2_4_19
void SobelFilter::SobelFilter_Add2i1u2_4_19(){
  SobelFilter_Add2i1u2_4_19_out1 = (s_reg_19.read() + 1ULL);
}
// resource: SobelFilter_Add2i1u2_4  instance: SobelFilter_Add2i1u2_4_20
void SobelFilter::SobelFilter_Add2i1u2_4_20(){
  SobelFilter_Add2i1u2_4_20_out1 = (s_reg_23.read() + 1ULL);
}
void SobelFilter::drive_filter_in1(){
  filter_in1 = SobelFilter_Add2u2Mul2i3u2_4_18_out1.read();
}
// resource: mux_12bx2i0c
void SobelFilter::drive_SobelFilter_Add2Mul2s12u8u12_4_21_in3(){
  if ( gs_ctrl0.read() ) {
    SobelFilter_Add2Mul2s12u8u12_4_21_in3 = s_reg_21.read();
  } else {
    SobelFilter_Add2Mul2s12u8u12_4_21_in3 = s_reg_22.read();
  }
}
// resource: mux_8bx2i0c
void SobelFilter::drive_SobelFilter_Add2Mul2s12u8u12_4_21_in2(){
  if ( gs_ctrl0.read() ) {
    SobelFilter_Add2Mul2s12u8u12_4_21_in2 = o_result_g_data.read();
  } else {
    SobelFilter_Add2Mul2s12u8u12_4_21_in2 = o_result_r_data.read();
  }
}
// resource: mux_12bx2i0c
void SobelFilter::drive_SobelFilter_Add2Mul2s12u8u12_4_21_in1(){
  if ( gs_ctrl0.read() ) {
    SobelFilter_Add2Mul2s12u8u12_4_21_in1 = (sc_int<12> ) (s_reg_25.read());
  } else {
    SobelFilter_Add2Mul2s12u8u12_4_21_in1 = (sc_int<12> )filter_out1.read();
  }
}
// resource: SobelFilter_Add2Mul2s12u8u12_4  instance: SobelFilter_Add2Mul2s12u8u12_4_21
void SobelFilter::SobelFilter_Add2Mul2s12u8u12_4_21(){
  SobelFilter_Add2Mul2s12u8u12_4_21_out1 = (
                                           SobelFilter_Add2Mul2s12u8u12_4_21_in3
                                           .read() + 
                                           SobelFilter_Add2Mul2s12u8u12_4_21_in2
                                           .read() * 
                                           SobelFilter_Add2Mul2s12u8u12_4_21_in1
                                           .read());
}
// resource: SobelFilter_Lti3u2_4  instance: SobelFilter_Lti3u2_4_22
void SobelFilter::SobelFilter_Lti3u2_4_22(){
  SobelFilter_Lti3u2_4_22_out1 = (/*imp*/sc_uint<1>)(s_reg_24.read() < (
                                 sc_uint<2> )3ULL);
}
// resource: SobelFilter_Lti3u2_4  instance: SobelFilter_Lti3u2_4_23
void SobelFilter::SobelFilter_Lti3u2_4_23(){
  SobelFilter_Lti3u2_4_23_out1 = (/*imp*/sc_uint<1>)(s_reg_23.read() < (
                                 sc_uint<2> )3ULL);
}
// resource: SobelFilter_Add2Mul2s12u8u12_4  instance: SobelFilter_Add2Mul2s12u8u12_4_25
void SobelFilter::SobelFilter_Add2Mul2s12u8u12_4_25(){
  SobelFilter_Add2Mul2s12u8u12_4_25_out1 = (s_reg_20.read() + o_result_b_data
                                           .read() * (sc_int<12> )s_reg_25
                                           .read());
}
// resource: regr_en_sc_4
void SobelFilter::drive_global_state(){
  if ( (i_rst.read() == 0ULL) ) {
    global_state = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      global_state = global_state_next.read();
      break;
    }
  }
}
// resource: mux_4bx2i1c
void SobelFilter::drive_global_state_next(){
  switch( (sc_uint<4>)(global_state.read()) ) {
  default:
    global_state_next = (global_state.read() + 1ULL);
    break;
  case 0ULL: case 9ULL: 
    global_state_next = 1ULL;
    break;
  case 5ULL: 
    if ( SobelFilter_Lti3u2_4_23_out1.read() ) {
      global_state_next = 1ULL;
    } else {
      if ( SobelFilter_Lti3u2_4_22_out1.read() ) {
        global_state_next = 1ULL;
      } else {
        global_state_next = (global_state.read() + 1ULL);
      }
    }
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_sc_1
void SobelFilter::drive_gs_ctrl0(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl0 = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    case 0ULL: 
      switch( (sc_uint<4>)(global_state_next.read()) ) {
      default:
        gs_ctrl0 = 0ULL;
        break;
      case 5ULL: 
        gs_ctrl0 = 1ULL;
        break;
      }
      break;
    }
  }
}
void SobelFilter::drive_i_r_busy(){
  i_r_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
             SobelFilter_gen_busy_r_4_30_out1.read().range(2,2)));
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_30
void SobelFilter::SobelFilter_gen_busy_r_4_30_p8(){
  SobelFilter_gen_busy_r_4_30_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)
                                     ((sc_bv<1>)(
                                     SobelFilter_gen_busy_r_4_30_gnew_req_i1
                                     .read()), 
                                     (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)(
                                     (sc_bv<1>)(
                                     SobelFilter_gen_busy_r_4_30_gdiv_i3.read())
                                     , 
                                     (sc_bv<1>)(SobelFilter_gen_busy_r_4_30_gen_busy_0_i_r_m_data_is_invalid_next
                                     .read())) ))) ));
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_30
void SobelFilter::SobelFilter_gen_busy_r_4_30_p7(){
  SobelFilter_gen_busy_r_4_30_gen_busy_0_i_r_m_data_is_invalid_next = ~(sc_uint<1>)SobelFilter_gen_busy_r_4_30_gdiv_i3
                                                                      .read();
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_30
void SobelFilter::SobelFilter_gen_busy_r_4_30_p6(){
  SobelFilter_gen_busy_r_4_30_gdiv_i3 = (sc_uint<1> ) (i_r_vld.read() & !
                                        SobelFilter_gen_busy_r_4_30_gnew_req_i1
                                        .read());
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_30
void SobelFilter::SobelFilter_gen_busy_r_4_30_p5(){
  SobelFilter_gen_busy_r_4_30_gnew_req_i1 = (sc_uint<1> ) (i_r_m_busy_req_0
                                            .read() & ( i_r_m_unvalidated_req
                                            .read() | (sc_uint<1> )i_r_vld
                                            .read() ));
}
// resource: regr_ss_1
void SobelFilter::drive_i_r_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_r_m_unvalidated_req = 1ULL;
  } else {
    i_r_m_unvalidated_req = (sc_uint<1> ) (SobelFilter_N_Muxb_1_2_11_4_10_out1
                            .read());
  }
}
// resource: SobelFilter_N_Muxb_1_2_11_4
void SobelFilter::SobelFilter_N_Muxb_1_2_11_4_10(){
  if ( i_r_m_busy_req_0.read() ) {
    SobelFilter_N_Muxb_1_2_11_4_10_out1 = (sc_uint<1> ) (i_r_m_unvalidated_req
                                          .read());
  } else {
    SobelFilter_N_Muxb_1_2_11_4_10_out1 = (sc_uint<1> ) (i_r_vld.read());
  }
}
void SobelFilter::drive_i_g_busy(){
  i_g_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
             SobelFilter_gen_busy_r_4_31_out1.read().range(2,2)));
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_31
void SobelFilter::SobelFilter_gen_busy_r_4_31_p8(){
  SobelFilter_gen_busy_r_4_31_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)
                                     ((sc_bv<1>)(
                                     SobelFilter_gen_busy_r_4_31_gnew_req_i1
                                     .read()), 
                                     (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)(
                                     (sc_bv<1>)(
                                     SobelFilter_gen_busy_r_4_31_gdiv_i3.read())
                                     , 
                                     (sc_bv<1>)(SobelFilter_gen_busy_r_4_31_gen_busy_0_i_r_m_data_is_invalid_next
                                     .read())) ))) ));
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_31
void SobelFilter::SobelFilter_gen_busy_r_4_31_p7(){
  SobelFilter_gen_busy_r_4_31_gen_busy_0_i_r_m_data_is_invalid_next = ~(sc_uint<1>)SobelFilter_gen_busy_r_4_31_gdiv_i3
                                                                      .read();
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_31
void SobelFilter::SobelFilter_gen_busy_r_4_31_p6(){
  SobelFilter_gen_busy_r_4_31_gdiv_i3 = (sc_uint<1> ) (i_g_vld.read() & !
                                        SobelFilter_gen_busy_r_4_31_gnew_req_i1
                                        .read());
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_31
void SobelFilter::SobelFilter_gen_busy_r_4_31_p5(){
  SobelFilter_gen_busy_r_4_31_gnew_req_i1 = (sc_uint<1> ) (i_g_m_busy_req_0
                                            .read() & ( i_g_m_unvalidated_req
                                            .read() | (sc_uint<1> )i_g_vld
                                            .read() ));
}
// resource: regr_ss_1
void SobelFilter::drive_i_g_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_g_m_unvalidated_req = 1ULL;
  } else {
    i_g_m_unvalidated_req = (sc_uint<1> ) (SobelFilter_N_Muxb_1_2_11_4_13_out1
                            .read());
  }
}
// resource: SobelFilter_N_Muxb_1_2_11_4
void SobelFilter::SobelFilter_N_Muxb_1_2_11_4_13(){
  if ( i_g_m_busy_req_0.read() ) {
    SobelFilter_N_Muxb_1_2_11_4_13_out1 = (sc_uint<1> ) (i_g_m_unvalidated_req
                                          .read());
  } else {
    SobelFilter_N_Muxb_1_2_11_4_13_out1 = (sc_uint<1> ) (i_g_vld.read());
  }
}
void SobelFilter::drive_i_b_busy(){
  i_b_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
             SobelFilter_gen_busy_r_4_32_out1.read().range(2,2)));
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_32
void SobelFilter::SobelFilter_gen_busy_r_4_32_p8(){
  SobelFilter_gen_busy_r_4_32_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)
                                     ((sc_bv<1>)(
                                     SobelFilter_gen_busy_r_4_32_gnew_req_i1
                                     .read()), 
                                     (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)(
                                     (sc_bv<1>)(
                                     SobelFilter_gen_busy_r_4_32_gdiv_i3.read())
                                     , 
                                     (sc_bv<1>)(SobelFilter_gen_busy_r_4_32_gen_busy_0_i_r_m_data_is_invalid_next
                                     .read())) ))) ));
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_32
void SobelFilter::SobelFilter_gen_busy_r_4_32_p7(){
  SobelFilter_gen_busy_r_4_32_gen_busy_0_i_r_m_data_is_invalid_next = ~(sc_uint<1>)SobelFilter_gen_busy_r_4_32_gdiv_i3
                                                                      .read();
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_32
void SobelFilter::SobelFilter_gen_busy_r_4_32_p6(){
  SobelFilter_gen_busy_r_4_32_gdiv_i3 = (sc_uint<1> ) (i_b_vld.read() & !
                                        SobelFilter_gen_busy_r_4_32_gnew_req_i1
                                        .read());
}
// resource: SobelFilter_gen_busy_r_4  instance: SobelFilter_gen_busy_r_4_32
void SobelFilter::SobelFilter_gen_busy_r_4_32_p5(){
  SobelFilter_gen_busy_r_4_32_gnew_req_i1 = (sc_uint<1> ) (i_b_m_busy_req_0
                                            .read() & ( i_b_m_unvalidated_req
                                            .read() | (sc_uint<1> )i_b_vld
                                            .read() ));
}
// resource: regr_ss_1
void SobelFilter::drive_i_b_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_b_m_unvalidated_req = 1ULL;
  } else {
    i_b_m_unvalidated_req = (sc_uint<1> ) (SobelFilter_N_Muxb_1_2_11_4_16_out1
                            .read());
  }
}
// resource: SobelFilter_N_Muxb_1_2_11_4
void SobelFilter::SobelFilter_N_Muxb_1_2_11_4_16(){
  if ( i_b_m_busy_req_0.read() ) {
    SobelFilter_N_Muxb_1_2_11_4_16_out1 = (sc_uint<1> ) (i_b_m_unvalidated_req
                                          .read());
  } else {
    SobelFilter_N_Muxb_1_2_11_4_16_out1 = (sc_uint<1> ) (i_b_vld.read());
  }
}
void SobelFilter::drive_o_result_r_vld(){
  o_result_r_vld = (sc_uint<1> ) (SobelFilter_Or_1Ux1U_1U_4_2_out1.read());
}
// resource: SobelFilter_Or_1Ux1U_1U_4  instance: SobelFilter_Or_1Ux1U_1U_4_2
void SobelFilter::SobelFilter_Or_1Ux1U_1U_4_2(){
  SobelFilter_Or_1Ux1U_1U_4_2_out1 = (sc_uint<1> ) (o_result_r_m_unacked_req
                                     .read() | (sc_uint<1>)
                                     SobelFilter_Xor_1Ux1U_1U_1_1_out1.read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_r_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_r_m_unacked_req = 0ULL;
  } else {
    o_result_r_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1Ux1U_1U_4_26_out1
                               .read());
  }
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_26
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_26(){
  SobelFilter_And_1Ux1U_1U_4_26_out1 = (sc_uint<1> ) (o_result_r_busy.read() & 
                                       o_result_r_vld.read());
}
// resource: SobelFilter_Xor_1Ux1U_1U_1  instance: SobelFilter_Xor_1Ux1U_1U_1_1
void SobelFilter::SobelFilter_Xor_1Ux1U_1U_1_1(){
  SobelFilter_Xor_1Ux1U_1U_1_1_out1 = (sc_uint<1> ) (o_result_r_m_req_m_trig_req
                                      .read() ^ o_result_r_m_req_m_prev_trig_req
                                      .read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_r_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_r_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_result_r_m_req_m_prev_trig_req = o_result_r_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1U_1  instance: SobelFilter_Not_1U_1U_1_3
void SobelFilter::SobelFilter_Not_1U_1U_1_3(){
  SobelFilter_Not_1U_1U_1_3_out1 = !o_result_r_m_req_m_trig_req.read();
}
void SobelFilter::drive_o_result_g_vld(){
  o_result_g_vld = (sc_uint<1> ) (SobelFilter_Or_1Ux1U_1U_4_5_out1.read());
}
// resource: SobelFilter_Or_1Ux1U_1U_4  instance: SobelFilter_Or_1Ux1U_1U_4_5
void SobelFilter::SobelFilter_Or_1Ux1U_1U_4_5(){
  SobelFilter_Or_1Ux1U_1U_4_5_out1 = (sc_uint<1> ) (o_result_g_m_unacked_req
                                     .read() | (sc_uint<1>)
                                     SobelFilter_Xor_1Ux1U_1U_1_4_out1.read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_g_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_g_m_unacked_req = 0ULL;
  } else {
    o_result_g_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1Ux1U_1U_4_27_out1
                               .read());
  }
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_27
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_27(){
  SobelFilter_And_1Ux1U_1U_4_27_out1 = (sc_uint<1> ) (o_result_g_busy.read() & 
                                       o_result_g_vld.read());
}
// resource: SobelFilter_Xor_1Ux1U_1U_1  instance: SobelFilter_Xor_1Ux1U_1U_1_4
void SobelFilter::SobelFilter_Xor_1Ux1U_1U_1_4(){
  SobelFilter_Xor_1Ux1U_1U_1_4_out1 = (sc_uint<1> ) (o_result_g_m_req_m_trig_req
                                      .read() ^ o_result_g_m_req_m_prev_trig_req
                                      .read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_g_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_g_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_result_g_m_req_m_prev_trig_req = o_result_g_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1U_1  instance: SobelFilter_Not_1U_1U_1_6
void SobelFilter::SobelFilter_Not_1U_1U_1_6(){
  SobelFilter_Not_1U_1U_1_6_out1 = !o_result_g_m_req_m_trig_req.read();
}
void SobelFilter::drive_o_result_b_vld(){
  o_result_b_vld = (sc_uint<1> ) (SobelFilter_Or_1Ux1U_1U_4_8_out1.read());
}
// resource: SobelFilter_Or_1Ux1U_1U_4  instance: SobelFilter_Or_1Ux1U_1U_4_8
void SobelFilter::SobelFilter_Or_1Ux1U_1U_4_8(){
  SobelFilter_Or_1Ux1U_1U_4_8_out1 = (sc_uint<1> ) (o_result_b_m_unacked_req
                                     .read() | (sc_uint<1>)
                                     SobelFilter_Xor_1Ux1U_1U_1_7_out1.read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_b_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_b_m_unacked_req = 0ULL;
  } else {
    o_result_b_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1Ux1U_1U_4_28_out1
                               .read());
  }
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_28
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_28(){
  SobelFilter_And_1Ux1U_1U_4_28_out1 = (sc_uint<1> ) (o_result_b_busy.read() & 
                                       o_result_b_vld.read());
}
// resource: SobelFilter_Xor_1Ux1U_1U_1  instance: SobelFilter_Xor_1Ux1U_1U_1_7
void SobelFilter::SobelFilter_Xor_1Ux1U_1U_1_7(){
  SobelFilter_Xor_1Ux1U_1U_1_7_out1 = (sc_uint<1> ) (o_result_b_m_req_m_trig_req
                                      .read() ^ o_result_b_m_req_m_prev_trig_req
                                      .read());
}
// resource: regr_sc_1
void SobelFilter::drive_o_result_b_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_result_b_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_result_b_m_req_m_prev_trig_req = o_result_b_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1U_1  instance: SobelFilter_Not_1U_1U_1_9
void SobelFilter::SobelFilter_Not_1U_1U_1_9(){
  SobelFilter_Not_1U_1U_1_9_out1 = !o_result_b_m_req_m_trig_req.read();
}
