// Generated by stratus_hls 19.12-s100  (91710.131054)
// Mon Apr 26 01:59:07 2021
// from ../SobelFilter.cpp
#ifndef CYNTH_PART_SobelFilter_SobelFilter_rtl_h
#define CYNTH_PART_SobelFilter_SobelFilter_rtl_h

#include "systemc.h"
/* Include declarations of instantiated parts. */
#include "SobelFilter_ROM_9X32_filter.h"


/* Declaration of the synthesized module. */
struct SobelFilter : public sc_module {
  sc_in<bool > i_clk;
  sc_in<bool > i_rst;
  sc_out<bool > i_rgb_busy;
  sc_in<bool > i_rgb_vld;
  sc_in<sc_uint<24> > i_rgb_data;
  sc_in<bool > o_result_busy;
  sc_out<bool > o_result_vld;
  sc_out<sc_uint<24> > o_result_data;
  SobelFilter( sc_module_name name );
  SC_HAS_PROCESS(SobelFilter);
  sc_signal<bool > o_result_m_req_m_prev_trig_req;
  sc_signal<sc_uint<1> > SobelFilter_Xor_1Ux1U_1U_1_1_out1;
  sc_signal<bool > o_result_m_unacked_req;
  sc_signal<sc_uint<1> > SobelFilter_Or_1Ux1U_1U_4_2_out1;
  sc_signal<sc_uint<1> > SobelFilter_N_Muxb_1_2_0_4_4_out1;
  sc_signal<bool > i_rgb_m_unvalidated_req;
  sc_signal<sc_uint<1> > 
  SobelFilter_gen_busy_r_4_20_gen_busy_i_rgb_m_data_is_invalid_next;
  sc_signal<sc_uint<1> > SobelFilter_gen_busy_r_4_20_gdiv;
  sc_signal<sc_uint<1> > SobelFilter_gen_busy_r_4_20_gnew_req;
  sc_signal<sc_uint<3> > global_state_next;
  sc_signal<sc_uint<12> > SobelFilter_Add_12Ux12U_12U_4_12_in1;
  sc_signal<sc_int<12> > SobelFilter_Mul_12Sx8U_12S_4_10_out1;
  sc_signal<sc_uint<8> > SobelFilter_Mul_12Sx8U_12S_4_10_in1;
  sc_signal<sc_int<12> > SobelFilter_Mul_12Sx8U_12S_4_10_in2;
  sc_signal<sc_uint<4> > SobelFilter_Add_4Ux2U_4U_4_8_out1;
  sc_signal<sc_uint<2> > SobelFilter_Mul_2Ux2U_4U_4_7_in2;
  sc_signal<sc_uint<2> > SobelFilter_Add_2Ux1U_2U_4_6_in2;
  sc_signal<sc_uint<1> > gs_ctrl0;
  sc_signal<sc_int<12> > SobelFilter_Mul_12Sx8U_12S_4_11_out1;
  sc_signal<sc_uint<12> > s_reg_28;
  sc_signal<sc_uint<12> > s_reg_27;
  sc_signal<sc_uint<4> > SobelFilter_Mul_2Ux2U_4U_4_7_out1;
  sc_signal<sc_uint<8> > s_reg_26;
  sc_signal<sc_uint<2> > SobelFilter_Add_2Ux1U_2U_4_9_out1;
  sc_signal<sc_uint<2> > s_reg_25;
  sc_signal<sc_uint<12> > s_reg_23;
  sc_signal<sc_uint<12> > s_reg_22;
  sc_signal<sc_uint<2> > SobelFilter_Add_2Ux1U_2U_4_6_out1;
  sc_signal<sc_uint<2> > s_reg_21;
  sc_signal<sc_uint<2> > s_reg_20;
  sc_signal<sc_uint<3> > SobelFilter_gen_busy_r_4_20_out1;
  sc_signal<sc_uint<1> > SobelFilter_And_1Ux1U_1U_4_18_out1;
  sc_signal<sc_uint<1> > SobelFilter_Not_1U_1U_1_3_out1;
  sc_signal<bool > o_result_m_req_m_trig_req;
  sc_signal<sc_uint<1> > SobelFilter_LessThan_2Ux2U_1U_4_15_out1;
  sc_signal<sc_uint<1> > SobelFilter_LessThan_2Ux2U_1U_4_17_out1;
  sc_signal<sc_uint<3> > global_state;
  sc_signal<bool > i_rgb_m_busy_req_0;
  sc_signal<sc_uint<12> > SobelFilter_Add_12Ux12U_12U_4_12_out1;
  sc_signal<sc_uint<12> > SobelFilter_Add_12Ux12U_12U_4_16_out1;
  sc_signal<sc_uint<12> > s_reg_24;
  sc_signal<sc_uint<1> > stall0;
  sc_signal<sc_uint<4> > filter_in1;
  sc_signal<sc_uint<32> > filter_out1;
  SobelFilter_ROM_9X32_filter *filter;
  void drive_o_result_data();
  void drive_i_rgb_m_busy_req_0();
  void drive_o_result_m_req_m_trig_req();
  void drive_stall0();
  void drive_s_reg_20();
  void drive_s_reg_21();
  void drive_s_reg_22();
  void drive_s_reg_23();
  void drive_s_reg_24();
  void drive_s_reg_25();
  void drive_s_reg_26();
  void drive_s_reg_27();
  void drive_s_reg_28();
  void drive_SobelFilter_Add_2Ux1U_2U_4_6_in2();
  void SobelFilter_Add_2Ux1U_2U_4_6();
  void drive_SobelFilter_Mul_2Ux2U_4U_4_7_in2();
  void SobelFilter_Mul_2Ux2U_4U_4_7();
  void SobelFilter_Add_4Ux2U_4U_4_8();
  void SobelFilter_Add_2Ux1U_2U_4_9();
  void drive_filter_in1();
  void drive_SobelFilter_Mul_12Sx8U_12S_4_10_in2();
  void drive_SobelFilter_Mul_12Sx8U_12S_4_10_in1();
  void SobelFilter_Mul_12Sx8U_12S_4_10();
  void SobelFilter_Mul_12Sx8U_12S_4_11();
  void drive_SobelFilter_Add_12Ux12U_12U_4_12_in1();
  void SobelFilter_Add_12Ux12U_12U_4_12();
  void SobelFilter_LessThan_2Ux2U_1U_4_15();
  void SobelFilter_Add_12Ux12U_12U_4_16();
  void SobelFilter_LessThan_2Ux2U_1U_4_17();
  void drive_global_state();
  void drive_global_state_next();
  void drive_gs_ctrl0();
  void drive_i_rgb_busy();
  void SobelFilter_gen_busy_r_4_20_p8();
  void SobelFilter_gen_busy_r_4_20_p7();
  void SobelFilter_gen_busy_r_4_20_p6();
  void SobelFilter_gen_busy_r_4_20_p5();
  void drive_i_rgb_m_unvalidated_req();
  void SobelFilter_N_Muxb_1_2_0_4_4();
  void drive_o_result_vld();
  void SobelFilter_Or_1Ux1U_1U_4_2();
  void drive_o_result_m_unacked_req();
  void SobelFilter_And_1Ux1U_1U_4_18();
  void SobelFilter_Xor_1Ux1U_1U_1_1();
  void drive_o_result_m_req_m_prev_trig_req();
  void SobelFilter_Not_1U_1U_1_3();
};

#endif
