// Generated by stratus_hls 19.12-s100  (91710.131054)
// Mon Apr 26 12:58:10 2021
// from ../SobelFilter.cpp

`timescale 1ps / 1ps

      
module SobelFilter_ROM_9X32_filter(in1, out1, clk);

      input [3:0] in1;
      input clk;
      output [31:0] out1;
      reg [31:0] out1;
      reg[31:0] filter[8:0];

         initial begin
            $readmemh("bdw_work/modules/SobelFilter/DPA/SobelFilter_ROM_9X32_filter_0.memh", filter);
         end

         always @(posedge clk)
          begin :SobelFilter_ROM_9X32_filter_filter_thread_1
            if (in1 < 4'd09) begin
               out1 <= filter[in1];
            end
         end


endmodule

