// Generated by stratus_hls 19.12-s100  (91710.131054)
// Mon Apr 26 02:09:13 2021
// from ../SobelFilter.cpp
#ifndef CYNTH_PART_SobelFilter_SobelFilter_rtl_h
#define CYNTH_PART_SobelFilter_SobelFilter_rtl_h

#include "systemc.h"
/* Include declarations of instantiated parts. */
#include "SobelFilter_ROM_9X32_filter.h"


/* Declaration of the synthesized module. */
struct SobelFilter : public sc_module {
  sc_in<bool > i_clk;
  sc_in<bool > i_rst;
  sc_out<bool > i_rgb_busy;
  sc_in<bool > i_rgb_vld;
  sc_in<sc_uint<24> > i_rgb_data;
  sc_in<bool > o_result_busy;
  sc_out<bool > o_result_vld;
  sc_out<sc_uint<24> > o_result_data;
  SobelFilter( sc_module_name name );
  SC_HAS_PROCESS(SobelFilter);
  sc_signal<bool > o_result_m_req_m_prev_trig_req;
  sc_signal<sc_uint<1> > SobelFilter_Xor_1Ux1U_1U_1_1_out1;
  sc_signal<bool > o_result_m_unacked_req;
  sc_signal<sc_uint<1> > SobelFilter_Or_1Ux1U_1U_4_2_out1;
  sc_signal<sc_uint<1> > SobelFilter_N_Muxb_1_2_11_4_4_out1;
  sc_signal<bool > i_rgb_m_unvalidated_req;
  sc_signal<sc_uint<1> > 
  SobelFilter_gen_busy_r_4_16_gen_busy_i_rgb_m_data_is_invalid_next;
  sc_signal<sc_uint<1> > SobelFilter_gen_busy_r_4_16_gdiv;
  sc_signal<sc_uint<1> > SobelFilter_gen_busy_r_4_16_gnew_req;
  sc_signal<sc_uint<3> > global_state_next;
  sc_signal<sc_int<12> > SobelFilter_Add2Mul2s12u8u12_4_9_in1;
  sc_signal<sc_uint<8> > SobelFilter_Add2Mul2s12u8u12_4_9_in2;
  sc_signal<sc_uint<12> > SobelFilter_Add2Mul2s12u8u12_4_9_in3;
  sc_signal<sc_uint<1> > gs_ctrl0;
  sc_signal<sc_uint<4> > SobelFilter_Add2u2Mul2i3u2_4_6_out1;
  sc_signal<sc_uint<8> > s_reg_24;
  sc_signal<sc_uint<12> > s_reg_23;
  sc_signal<sc_uint<8> > s_reg_22;
  sc_signal<sc_uint<2> > SobelFilter_Add2i1u2_4_7_out1;
  sc_signal<sc_uint<2> > SobelFilter_Add2i1u2_4_8_out1;
  sc_signal<sc_uint<2> > s_reg_20;
  sc_signal<sc_uint<12> > s_reg_18;
  sc_signal<sc_uint<12> > s_reg_17;
  sc_signal<sc_uint<2> > s_reg_21;
  sc_signal<sc_uint<2> > s_reg_16;
  sc_signal<sc_uint<3> > SobelFilter_gen_busy_r_4_16_out1;
  sc_signal<sc_uint<1> > SobelFilter_And_1Ux1U_1U_4_14_out1;
  sc_signal<sc_uint<1> > SobelFilter_Not_1U_1U_1_3_out1;
  sc_signal<bool > o_result_m_req_m_trig_req;
  sc_signal<sc_uint<1> > SobelFilter_Lti3u2_4_10_out1;
  sc_signal<sc_uint<1> > SobelFilter_Lti3u2_4_11_out1;
  sc_signal<sc_uint<3> > global_state;
  sc_signal<bool > i_rgb_m_busy_req_0;
  sc_signal<sc_uint<12> > SobelFilter_Add2Mul2s12u8u12_4_13_out1;
  sc_signal<sc_uint<12> > SobelFilter_Add2Mul2s12u8u12_4_9_out1;
  sc_signal<sc_uint<12> > s_reg_19;
  sc_signal<sc_uint<1> > stall0;
  sc_signal<sc_uint<4> > filter_in1;
  sc_signal<sc_uint<32> > filter_out1;
  SobelFilter_ROM_9X32_filter *filter;
  void drive_o_result_data();
  void drive_i_rgb_m_busy_req_0();
  void drive_o_result_m_req_m_trig_req();
  void drive_stall0();
  void drive_s_reg_16();
  void drive_s_reg_17();
  void drive_s_reg_18();
  void drive_s_reg_19();
  void drive_s_reg_20();
  void drive_s_reg_21();
  void drive_s_reg_22();
  void drive_s_reg_23();
  void drive_s_reg_24();
  void SobelFilter_Add2u2Mul2i3u2_4_6();
  void SobelFilter_Add2i1u2_4_7();
  void SobelFilter_Add2i1u2_4_8();
  void drive_filter_in1();
  void drive_SobelFilter_Add2Mul2s12u8u12_4_9_in3();
  void drive_SobelFilter_Add2Mul2s12u8u12_4_9_in2();
  void drive_SobelFilter_Add2Mul2s12u8u12_4_9_in1();
  void SobelFilter_Add2Mul2s12u8u12_4_9();
  void SobelFilter_Lti3u2_4_10();
  void SobelFilter_Lti3u2_4_11();
  void SobelFilter_Add2Mul2s12u8u12_4_13();
  void drive_global_state();
  void drive_global_state_next();
  void drive_gs_ctrl0();
  void drive_i_rgb_busy();
  void SobelFilter_gen_busy_r_4_16_p8();
  void SobelFilter_gen_busy_r_4_16_p7();
  void SobelFilter_gen_busy_r_4_16_p6();
  void SobelFilter_gen_busy_r_4_16_p5();
  void drive_i_rgb_m_unvalidated_req();
  void SobelFilter_N_Muxb_1_2_11_4_4();
  void drive_o_result_vld();
  void SobelFilter_Or_1Ux1U_1U_4_2();
  void drive_o_result_m_unacked_req();
  void SobelFilter_And_1Ux1U_1U_4_14();
  void SobelFilter_Xor_1Ux1U_1U_1_1();
  void drive_o_result_m_req_m_prev_trig_req();
  void SobelFilter_Not_1U_1U_1_3();
};

#endif
