// Generated by stratus_hls 19.12-s100  (91710.131054)
// Mon Apr 26 01:59:07 2021
// from ../SobelFilter.cpp
#ifndef CYNTH_PART_SobelFilter_SobelFilter_ROM_9X32_filter_h
#define CYNTH_PART_SobelFilter_SobelFilter_ROM_9X32_filter_h

#include "systemc.h"
#include "cynthhl.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */

struct SobelFilter_ROM_9X32_filter : public sc_module {
  sc_in<sc_uint<4> > in1;
  sc_out<sc_uint<32> > out1;
  sc_in<bool > clk;
  SobelFilter_ROM_9X32_filter( sc_module_name name );
  SC_HAS_PROCESS(SobelFilter_ROM_9X32_filter);
  /*const*/ sc_uint<32> filter[9];
  void SobelFilter_ROM_9X32_filter_filter_thread_1();
};

#endif
