`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Apr 26 2021 12:38:13 CST (Apr 26 2021 04:38:13 UTC)

module SobelFilter_Xor_1Ux1U_1U_4(in2, in1, out1);
  input in2, in1;
  output out1;
  wire in2, in1;
  wire out1;
  XOR2XL g10(.A (in2), .B (in1), .Y (out1));
endmodule


